name: "Upload to Public S3"
description: "Upload to S3 with public-read ACL"

inputs:
  region:
    description: "AWS Region (AWS_REGION)"
    required: true
  access-key-id:
    description: "AWS Access Key ID (AWS_ACCESS_KEY_ID)"
    required: true
  secret-access-key:
    description: "AWS Secret Access Key (AWS_SECRET_ACCESS_KEY)"
    required: true
  src:
    description: "Path to file to upload"
    required: true
  dest:
    description: "S3 upload destination: '<bucket>/<key>'"
    required: true
  copies:
    description: "S3 copy destinations (multi-line): '<bucket>/<key>'"
outputs:
  public-url:
    description: "Public S3 URL of uploaded object (first if multiple copies)"

runs:
  using: "node16"
  main: "index.js"
